apps/accounts/urls.py
from django.conf.urls import url
from apps.accounts.views import *

app_name = 'accounts'
urlpatterns = [
    url(r'^sign-in$', SigninView.as_view(), name='signin'),
    url(r'^signup$', SignupView.as_view(), name='signup'),
    url(r'^lost-password', LostPasswordView.as_view(), name='lost_password'),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        ResetPasswordView.as_view(), name='reset_password'),
    url(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', confirm_email,
        name='confirm_email'),
    url(r'^logout$', sign_out, name='logout'),
]

config/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.generic import TemplateView
from apps.books.views import BookList
from .api import router


urlpatterns = [
    url(r'^$', BookList.as_view(), name='home'),
    url(r'^privacy/$',
        TemplateView.as_view(template_name='pages/privacy.html'), name='privacy'),

    # Users management
    url(r'^users/', include('apps.accounts.urls', namespace='users')),
    url(r'^books/', include('apps.books.urls', namespace='books')),
    path('api/', include(router.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

apps/accounts/models.py
# from django.db import models
# from django.contrib.auth.models import User
# from django.db.models.signals import post_save
# from django.dispatch import receiver
#
#
# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

apps/accounts/forms.py
import datetime
from django.contrib.auth import authenticate
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


class SignUpForm(forms.ModelForm):
    placeholders = {
        'username': _('Your username'),
        'email': _('Your email'),
        'password': _('Password'),
        'repeat_password': _('Repeat password')
    }

    username = forms.CharField(max_length=64, label=_("Username"))
    email = forms.EmailField(max_length=64, label=_("Email"))
    repeat_password = forms.CharField(widget=forms.PasswordInput,  label=_('Password again'))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password']
        labels = {
            'password': _('Password'),
        }

        widgets = {
            'password': forms.PasswordInput
        }

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages['required'] = _('This field is required.')
            self.fields[field].widget.attrs.update({
                'placeholder': self.placeholders[field]
            })

    def clean_repeat_password(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('repeat_password'):
            raise forms.ValidationError(_("Passwords do not match."))

    def save(self, commit=True):
        _user = super(SignUpForm, self).save(commit=False)
        _user.set_password(self.cleaned_data["password"])
        _user.is_active = False
        _user.email = self.cleaned_data['email']

        if commit:
            _user.save()

        return _user


class SignInForm(forms.Form):
    placeholders = {
        'username': _('Your username'),
        'password': _('Enter password')
    }

    username = forms.CharField(label=_('Email'))
    password = forms.CharField(widget=forms.PasswordInput, label=_('Password'))

    class Meta:
        labels = {
            'username': _('Username'),
            'password': _('Enter password'),
        }

    def __init__(self, *args, **kwargs):
        super(SignInForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages['required'] = _('This field is required.')
            self.fields[field].widget.attrs.update({
                'placeholder': self.placeholders[field]
            })

    def clean(self):
        if not authenticate(username=self.cleaned_data.get('username'), password=self.cleaned_data.get('password')):
            raise forms.ValidationError({'password': [_('Incorrect login or password.')]})


class LostPasswordForm(forms.Form):
    placeholders = {
        'email': _('Email')
    }

    email = forms.EmailField(label='')

    class Meta:
        labels = {
            'email': _('Электронный адрес')
        }

    def __init__(self, *args, **kwargs):
        super(LostPasswordForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages['required'] = _('Please write your email address.')
            self.fields[field].widget.attrs.update({
                'placeholder': self.placeholders[field]
            })

    def clean(self):
        try:
            user = User.objects.get(email=self.cleaned_data.get('email'))
        except:
            raise forms.ValidationError({'email': [_('This email address is not registered.')]})


class ResetPasswordForm(forms.Form):
    placeholders = {
        'password': _('New password'),
        'repeat_password': _('Repeat new password'),
    }

    password = forms.CharField(widget=forms.PasswordInput)
    repeat_password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': self.placeholders[field]
            })

    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('repeat_password'):
            raise forms.ValidationError(_('The passwords you entered do not match.'))

apps/accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import View
from .tasks import *
from .mixins import AnonymousMixin
from .forms import SignUpForm, SignInForm, LostPasswordForm, ResetPasswordForm


class SigninView(AnonymousMixin, View):
    def get(self, request):
        form = SignInForm()
        return render(request, 'accounts/signin.html', locals())

    def post(self, request):
        form = SignInForm(request.POST)
        if form.is_valid():
            _user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if _user is not None:
                login(request, _user)
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                else:
                    return redirect(reverse('home'))
        else:
            return render(request, 'accounts/signin.html', locals())


class SignupView(AnonymousMixin, View):
    success = False

    def get(self, request):
        form = SignUpForm()
        return render(request, 'accounts/signup.html', locals())

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            success = True

            token = default_token_generator.make_token(f)
            uid = urlsafe_base64_encode(force_bytes(f.pk))
            title = 'Account activation at demo-books-django'
            message = render_to_string('emails/signup.html',
                                       {'link': request.build_absolute_uri(reverse('users:confirm_email',
                                                                                   kwargs={'uidb64': uid, 'token': token}))})
            AsyncEmail(f.email,title,message)
        return render(request, 'accounts/signup.html', locals())


class LostPasswordView(AnonymousMixin, View):

    def get(self, request):
        success = False
        if request.user.is_authenticated:
            return redirect(reverse('home'))
        form = LostPasswordForm()
        return render(request, 'accounts/lost-password.html', locals())

    def post(self, request):
        form = LostPasswordForm(request.POST)
        success = False
        if form.is_valid():
            success = True
            user = User.objects.get(email=form.cleaned_data.get('email'))
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            title = 'Reset password at demo-books-django'
            message = render_to_string('emails/reset-password.html', {
                'email': user.email, 'link': request.build_absolute_uri(reverse('users:reset_password',
                                                                                kwargs={'uidb64': uid, 'token': token}))})
            AsyncEmail(user.email,title,message)
        return render(request, 'accounts/lost-password.html', locals())


class ResetPasswordView(AnonymousMixin, View):

    def get(self, request, uidb64, token):
        success = False
        form = ResetPasswordForm()
        return render(request, 'accounts/reset-password.html', locals())

    def post(self, request, uidb64, token):
        success = False
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            if uidb64 is not None and token is not None:
                uid = urlsafe_base64_decode(uidb64)
                try:
                    user_model = get_user_model()
                    user = user_model.objects.get(pk=uid)
                    if default_token_generator.check_token(user, token):
                        print(form.cleaned_data.get('password'))
                        user.set_password(form.cleaned_data.get('password'))
                        user.save()
                        success = True
                        return redirect(reverse('users:signin'))
                except:
                    return HttpResponse('Activation link is invalid!')
        return render(request, 'accounts/reset-password.html', locals())


def confirm_email(request, uidb64, token):
    if uidb64 is not None and token is not None:
        uid = urlsafe_base64_decode(uidb64)
        try:
            user_model = get_user_model()
            user = user_model.objects.get(pk=uid)
            # print(user)
            if default_token_generator.check_token(user, token) and user.is_active is False:
                user.is_active = True
                user.save()
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect(reverse('home'))
            else:
                return HttpResponse('Activation link is invalid!')
        except User.DoesNotExist:
            return HttpResponse('Error!')
    return redirect(reverse('home'))


@login_required
def sign_out(request):
    logout(request)
    return redirect(reverse('users:signin'))

templates/accounts/lost-password.html
{% extends 'base.html' %}

{% load i18n static %}

{% block title %}Password recovery{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
    <div class="wrapper-signin-page">
        <div class="block">
			<div class="title">Password recovery</div>
            {% if not success %}<p class="info-message">Please enter your email. You will receive an email with a link to create a new password.</p>{% endif %}
            <form action="{% url 'users:lost_password' %}" method="post">
                {% csrf_token %}
                {% if success %}
                    <ol class="form_messages_list">
                        <li>Check your email. <br> We sent the instructions for password recovery to the email address you provided.</li>
                    </ol>
                {% else %}
                    {% if form.errors %}
                        <ol class="form_messages_list error">
                            {% for field in form %}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </ol>
                    {% endif %}
                    {% for field in form %}
                        <div class="form__item {{ field.has_error }}">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="form__item">
                        <button id="submit">Get new password</button>
                    </div>
                {% endif %}
            </form>
		</div>
        <div class="upper-block">
            <a href="{% url 'users:signin' %}">Sign in</a>
            <a href="{% url 'users:signup' %}">Sign up</a>
        </div>
	</div>
{% endblock %}

{% block extra_footer %}{% endblock %}

templates/accounts/reset-password.html
{% extends 'base.html' %}

{% load i18n static %}

{% block title %}Setting new password{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
    <div class="wrapper-signin-page">
        <div class="block">
			<div class="title">Setting new password</div>
            <p class="info-message">You requested a password change. On this page you can set a new password for your account.</p>
            <form action="" method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <ol class="form_messages_list error">
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ol>
                {% endif %}
                {% for field in form %}
                    <div class="form__item {{ field.has_error }}">
{#                        {{ field.label_tag }}#}
                        {{ field }}
                    </div>
                {% endfor %}
                <div class="form__item">
                    <button id="submit">Set new password</button>
                </div>
            </form>
		</div>
        <div class="upper-block">
            <a href="{% url 'users:signin' %}">Sign in</a>
            <a href="{% url 'users:signup' %}">Sign up</a>
        </div>
	</div>
{% endblock %}

{% block extra_footer %}{% endblock %}

templates/accounts/signin.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Sign in{% endblock %}

{% block extra_header %}{% endblock %}

{% block content %}
	<div class="container wrapper-signin-page">
        <div class="block">
        <div class="title">Sign in</div>
            <form action="{% url 'users:signin' %}" method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <ol class="form_messages_list error">
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ol>
                {% endif %}
                {% for field in form %}
                    <div class="form__item {{ field.has_error }}">
{#                        {{ field.label_tag }}#}
                        {{ field }}
                    </div>
                {% endfor %}
                <div class="form__item">
                    <button id="submit">Sign in</button>
                </div>
                <div class="form__item forgot-password">
                    <a href="{% url 'users:signup' %}">Sign up</a><a href="{% url 'users:lost_password' %}">Forgot password?</a>
                </div>
                <div class="title title-social">Social sign in</div>
                <div class="social">
                    <a class="btn-social-fb" href="{% url 'social:begin' 'facebook' %}?next={{ request.GET.next }}">Facebook</a>
                    <a class="btn-social-gh" href="{% url 'social:begin' 'github' %}?next={{ request.GET.next }}">GitHub</a>
                    <a class="btn-social-gg" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.GET.next }}">Google</a>
                </div>
            </form>
{#            <div class="title">or sign in using social network</div>#}
        </div>
	</div>
{% endblock %}

{% block extra_footer %}{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Sign up{% endblock %}

{% block extra_header %}{% endblock %}

{% block content %}
	<div class="container wrapper-signin-page">
        <div class="block">
        <div class="title">Sign up</div>
            <form action="{% url 'users:signup' %}" method="post">
                {% csrf_token %}
                {% if success == True %}
                    <ol class="form_messages_list"><li>Please, activate your account. We sent you an activation link.</li></ol>
                {% endif %}
                {% if form.errors %}
                    <ol class="form_messages_list error">
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    </ol>
                {% endif %}
                {% for field in form %}
                    <div class="form__item {{ field.has_error }}">
{#                        {{ field.label_tag }}#}
                        {{ field }}
                    </div>
                {% endfor %}
                <div class="form__item">
                    <button id="submit">Sign up</button>
                </div>
                <div class="form__item forgot-password">
                    <a href="{% url 'users:signin' %}">Sign in</a><a href="{% url 'users:lost_password' %}">Forgot password?</a>
                </div>
                <div class="title title-social">Social sign up</div>
                <div class="social">
                    <a class="btn-social-fb" href="{% url 'social:begin' 'facebook' %}?next=/">Facebook</a>
                    <a class="btn-social-gh" href="{% url 'social:begin' 'github' %}?next=/">GitHub</a>
                    <a class="btn-social-gg" href="{% url 'social:begin' 'google-oauth2' %}?next=/">Google</a>
                </div>
            </form>
{#            <div class="title">or sign in using social network</div>#}
        </div>
	</div>
{% endblock %}

{% block extra_footer %}{% endblock %}