apps/accounts/urls.py
from django.conf.urls import url
from apps.accounts.views import *

app_name = 'accounts'
urlpatterns = [
    url(r'^sign-in$', SigninView.as_view(), name='signin'),
    url(r'^signup$', SignupView.as_view(), name='signup'),
    url(r'^lost-password', LostPasswordView.as_view(), name='lost_password'),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        ResetPasswordView.as_view(), name='reset_password'),
    url(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', confirm_email,
        name='confirm_email'),
    url(r'^logout$', sign_out, name='logout'),
]

apps/books/urls.py
from django.conf.urls import url
from apps.books.views import *

app_name = 'books'
urlpatterns = [
    url(r'^add$', BookAdd.as_view(), name='add'),
    url(r'^my$', MyBookList.as_view(), name='my'),
    url(r'^(?P<book_id>[0-9]+)$', BookView.as_view(), name='item'),
    url(r'^(?P<book_id>[0-9]+)/mark-as-read$', ReadBookView.as_view(), name='read'),
    url(r'^(?P<book_id>[0-9]+)/edit$', BookEdit.as_view(), name='edit'),
    url(r'^(?P<book_id>[0-9]+)/delete$', BookDelete.as_view(), name='delete'),
]

config/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.generic import TemplateView
from apps.books.views import BookList
from .api import router


urlpatterns = [
    url(r'^$', BookList.as_view(), name='home'),
    url(r'^privacy/$',
        TemplateView.as_view(template_name='pages/privacy.html'), name='privacy'),

    # Users management
    url(r'^users/', include('apps.accounts.urls', namespace='users')),
    url(r'^books/', include('apps.books.urls', namespace='books')),
    path('api/', include(router.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

apps/books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from config.storage import PublicMediaStorage
from sorl.thumbnail import get_thumbnail


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Category(models.Model):
    slug = models.SlugField(blank=True, null=True, max_length=255, unique=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Cover(models.Model):
    file = models.ImageField(storage=PublicMediaStorage())
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def thumbnail(self):
        return get_thumbnail(self.file, '300x500', crop='center', quality=99).url


class Book(models.Model):
    cover = models.ForeignKey(Cover, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    authors = models.ManyToManyField(Author)
    categories = models.ManyToManyField(Category)
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)
    publication_date = models.DateTimeField(auto_now_add=True)

    def link(self):
        return reverse('books:item', args=[self.id])


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    date = models.DateField(auto_now_add=True)


class ReadBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    read_date = models.DateField(auto_now_add=True)

apps/books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.views.generic import View
from django.shortcuts import render, redirect
from rest_framework import viewsets, generics
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response

from apps.books.models import ReadBook
from apps.books.serializers import *
from apps.books.permissions import *


class BookList(View):
    def get(self, request):
        books = Book.objects.all().order_by('-id')
        return render(request, 'pages/home.html', locals())


class MyBookList(LoginRequiredMixin, View):
    def get(self, request):
        books = Book.objects.filter(publisher=request.user).order_by('-id')

        read_books = Book.objects.filter(
            id__in=[rbook.book.id for rbook in ReadBook.objects.filter(user=request.user)]
        )
        return render(request, 'pages/my-books.html', locals())


class BookView(View):
    def get(self, request, book_id):
        try:
            book = Book.objects.get(pk=book_id)
        except Book.DoesNotExist:
            raise Http404
        return render(request, 'pages/book-view.html', locals())


class BookAdd(LoginRequiredMixin, View):
    def get(self, request):
        page_title = 'Add a new book to the catalog'
        is_edit = 0
        book_id = 0
        return render(request, 'pages/add-book.html', locals())


class BookEdit(LoginRequiredMixin, View):
    def get(self, request, book_id):
        try:
            book = Book.objects.get(pk=book_id)
            page_title = 'Edit book "{}"'.format(book.title)
            is_edit = 1
            book_id = book.id
            if book.publisher != request.user:
                raise Http404

            return render(request, 'pages/add-book.html', locals())
        except Book.DoesNotExist:
            raise Http404


class BookDelete(LoginRequiredMixin, View):
    def get(self, request, book_id):
        try:
            book = Book.objects.get(pk=book_id)
            if book.publisher == request.user:
                book.delete()
                return redirect(reverse('books:my'))
            else:
                raise Http404
        except Book.DoesNotExist:
            raise Http404


class ReadBookView(LoginRequiredMixin, View):
    def get(self, request, book_id):
        try:
            book = Book.objects.get(pk=book_id)
            ReadBook.objects.create(book=book, user=request.user)
            return redirect(book.link())
        except Book.DoesNotExist:
            raise Http404


class BookViewset(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookListSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, IsOwnerOrReadIsAuthenticatedOnly)

    def perform_create(self, serializer):
        serializer.save(publisher=self.request.user)
        return serializer.instance

    def create(self, request, *args, **kwargs):
        write_serializer = BookCreateSerializer(data=request.data)
        write_serializer.is_valid(raise_exception=True)
        instance = self.perform_create(write_serializer)
        read_serializer = BookListSerializer(instance)

        return Response(read_serializer.data)


class CoverViewset(viewsets.ModelViewSet):
    queryset = Cover.objects.all()
    serializer_class = CoverSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)
    http_method_names = ['get', 'post', 'head', 'put']


class ReviewViewset(viewsets.ModelViewSet):
    queryset = Review.objects.none()
    serializer_class = ReviewSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, IsOwnerOrReadIsAuthenticatedOnly)

    def get_queryset(self):
        queryset = Review.objects.none()
        book_id = self.request.query_params.get('book_id', None)
        if book_id is not None:
            queryset = Review.objects.filter(book_id=book_id)
        return queryset

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class AuthorViewset(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)


class CategoryViewset(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)

templates/pages/add-book.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <div class="content">
        <div id="add-book" class="block">
            <div class="title">{{ page_title }}</div>
            <div class="v-cloak-loader page-loader" v-cloak></div>
            <form v-cloak>
                <input type="hidden" name="is_edit" value="{{ is_edit }}">
                <input type="hidden" value="{{ book_id }}" name="book_id">
                <div class="book-adding-form">
                    <div class="upload-cover-wrapper">
                        <div>
                            <div class="page-loader" v-show="cover_loading"></div>
                            <img src="" alt="" :src="cover_object.thumbnail" v-show="!cover_loading">
                            <label for="cover" class="cover-note"><span v-show="!cover_loading">Upload book cover</span></label>
                            <input type="file" id="cover" name="cover" ref="cover" accept="image/png, image/jpeg" v-on:change="uploadCover()"/>
                        </div>
                    </div>
                    <div class="form__items">
                        <div class="form__item">
                            <label for="title">Book title</label>
                            <input id="title" type="text" v-model="book_object.title"/>
                        </div>
                        <div class="form__item form__item-flex">
                            <div>
                                <label for="book_authors">Choose authors</label>
                                <select v-model="book_object.authors" id="book_authors" multiple>
                                    <option v-for="author in authors" :value="author.id">[[author.first_name]] [[author.last_name]]</option>
                                </select>
                            </div>
                            <div class="small-form">
                                <label for="first_name">Or add new one</label>
                                <div class="form-flex">
                                    <div class="form__item form__item-flex"><input type="text" id="first_name" placeholder="First name" v-model="author.first_name"><input  v-model="author.last_name" type="text" placeholder="Last name"></div>
                                    <div class="form__item"><button @click.prevent="addAuthor()">Add new author</button></div>
                                </div>
                            </div>
                        </div>
                        <div class="form__item form__item-flex">
                            <div>
                               <label for="book_cats">Choose categories</label>
                                <select v-model="book_object.categories" id="book_cats" multiple>
                                    <option v-for="category in categories" :value="category.id">[[category.name]]</option>
                                </select>
                            </div>
                            <div class="small-form">
                                <label for="cat_name">Or add new one</label>
                                <div class="form-flex">
                                    <div class="form__item"><input type="text" id="cat_name" placeholder="New category name" v-model="category.name"></div>
                                    <div class="form__item"><button @click.prevent="addCategory()">Add new category</button></div>
                                </div>
                            </div>
                        </div>
                         <div class="form__item">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" v-model="book_object.description" cols="30" rows="10"></textarea>
                        </div>
                        <div class="form__item">
                            <button class="button" :class="{loading: is_loading}" @click.prevent="addUpdateBook()">
                                <span class="loading_button"><span class="loader"></span></span>
                                <span class="loading_button_hide">Submit</span>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_footer %}
    <script src="{% static 'js/book-add.js' %}"></script>
{% endblock %}

templates/pages/book-view.html
{% extends 'base.html' %}
{% load static help_tags %}
{% block title %}{{ book.title }}{% endblock %}

{% block content %}
    {% is_read book request.user as is_read %}
    {% is_publisher book request.user as is_publisher %}
    <div class="content">
        <div class="block">
            <div class="title">
                {{ book.title }}
                {% if is_read %}
                    <p class="mark-as-read done">☑ Marked as read</p>
                {% else %}
                    <a href="{% url 'books:read' book.id %}" class="mark-as-read">Mark as read</a>
                {% endif %}
            </div>
            <article id="book-view" class="book__view">
                <div class="book__view-cover">
                    <figure>
                        <img src="{{ book.cover.thumbnail }}" alt="{{ book.title }}">
                    </figure>
                    {% if is_publisher %}
                        <a href="{% url 'books:edit' book.id %}" class="book-edit-link">✏️ Edit book</a><br>
                        <a href="{% url 'books:delete' book.id %}" class="book-delete-link" onclick="return confirm('Are you sure to delete this book?')">🗑️️ Detele book</a>
                    {% endif %}
                </div>
                <div class="book__view-info">
                    <input type="hidden" name="book_id" value="{{ book.id }}">
                    <h2>Authors</h2>
                    <p>
                        {% for author in book.authors.all %}
                            {{ author }}
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <h2>Categories</h2>
                    <p>
                        {% for category in book.categories.all %}
                            {{ category }}
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <h2>Description</h2>
                    <p>{{ book.description }}</p>
                    <h2>Reviews</h2>
                    <div class="reviews__list" v-if="reviews.length > 0" v-cloak>
                        <div class="reviews__list-item" v-for="review in reviews">
                            <div class="reviews__list-username">[[review.username]]</div>
                            <div class="reviews__list-text">
                                [[review.text]]
                            </div>
                        </div>
                    </div>
                    <div v-else>
                        <p>There is no one review. Be first leave a review.</p>
                    </div>
                    <h2>Leave a review</h2>
                    {% if request.user.is_authenticated %}
                    <form action="#">
                        <textarea v-model="review_object.text" name="your_review" id="your_review" cols="30" rows="10" placeholder="Type here your review"></textarea>
                        <div class="form__item">
                            <button class="button" :class="{loading: is_loading}" @click.prevent="addReview()">
                                <span class="loading_button"><span class="loader"></span></span>
                                <span class="loading_button_hide">Submit review</span>
                            </button>
                        </div>
                    </form>
                    {% else %}
                        <p>Please, <a href="{% url 'users:signin' %}?next={{ request.path }}">sign in</a> your account to leave a review.</p>
                    {% endif %}
                </div>
            </article>
        </div>
    </div>
{% endblock %}

{% block extra_footer %}
    <script src="{% static 'js/book-view.js' %}"></script>
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Book catalog{% endblock %}

{% block content %}
    <div class="content">
        <div class="block">
            <div class="books__list">
            {% for book in books %}
                <article class="book__item">
                    <figure>
                        <img src="{{ book.cover.thumbnail }}" alt="{{ book.title }}">
                    </figure>
                    <h2>{{ book.title }}</h2>
                    <p>by
                        {% for author in book.authors.all %}
                            {{ author }}
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <a href="{{ book.link }}">Read more</a>
                </article>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/my-books.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My books{% endblock %}

{% block content %}
    <div class="content">
        <div class="block">
            <div class="title">Books you've read</div>
            <div class="books__list">
                {% for book in read_books %}
                    <article class="book__item">
                        <figure>
                            <img src="{{ book.cover.thumbnail }}" alt="{{ book.title }}">
                        </figure>
                        <h2>{{ book.title }}</h2>
                        <p>by
                            {% for author in book.authors.all %}
                                {{ author }}
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                        <a href="{{ book.link }}">Read more</a>
                    </article>
                {% endfor %}
            </div>
            <div class="title">Books you've added</div>
            <div class="books__list">
                {% for book in books %}
                    <article class="book__item">
                        <figure>
                            <img src="{{ book.cover.thumbnail }}" alt="{{ book.title }}">
                        </figure>
                        <h2>{{ book.title }}</h2>
                        <p>by
                            {% for author in book.authors.all %}
                                {{ author }}
                                {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                        <a href="{{ book.link }}">Read more</a>
                    </article>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}