apps/accounts/urls.py
from django.conf.urls import url
from apps.accounts.views import *

app_name = 'accounts'
urlpatterns = [
    url(r'^sign-in$', SigninView.as_view(), name='signin'),
    url(r'^signup$', SignupView.as_view(), name='signup'),
    url(r'^lost-password', LostPasswordView.as_view(), name='lost_password'),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        ResetPasswordView.as_view(), name='reset_password'),
    url(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', confirm_email,
        name='confirm_email'),
    url(r'^logout$', sign_out, name='logout'),
]

apps/books/urls.py
from django.conf.urls import url
from apps.books.views import *

app_name = 'books'
urlpatterns = [
    url(r'^add$', BookAdd.as_view(), name='add'),
    url(r'^my$', MyBookList.as_view(), name='my'),
    url(r'^(?P<book_id>[0-9]+)$', BookView.as_view(), name='item'),
    url(r'^(?P<book_id>[0-9]+)/mark-as-read$', ReadBookView.as_view(), name='read'),
    url(r'^(?P<book_id>[0-9]+)/edit$', BookEdit.as_view(), name='edit'),
    url(r'^(?P<book_id>[0-9]+)/delete$', BookDelete.as_view(), name='delete'),
]

config/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.generic import TemplateView
from apps.books.views import BookList
from .api import router


urlpatterns = [
    url(r'^$', BookList.as_view(), name='home'),
    url(r'^privacy/$',
        TemplateView.as_view(template_name='pages/privacy.html'), name='privacy'),

    # Users management
    url(r'^users/', include('apps.accounts.urls', namespace='users')),
    url(r'^books/', include('apps.books.urls', namespace='books')),
    path('api/', include(router.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

templates/includes/footer.html
<footer class="footer-container">
    <div class="content">
        <div>
            demo-books-django.herokuapp.com &copy; 2019
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}

<header>
    <div class="header-content">
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}" class="btn btn-dual mr-1">
                        <span>demo-books-django</span>
                    </a>
                </li>
            </ul>
        </nav>
        <nav class="right">
            <ul>
                <li><a href="{% url 'books:my' %}" class="btn btn-dual mr-1">My books</a></li>
                <li><a href="{% url 'books:add' %}" class="btn btn-dual mr-1">Add book</a></li>
                {% if not request.user.is_authenticated %}
{#                        <li><a href="#"></a></li>#}
                    <li><a href="{% url 'users:signin' %}" class="btn btn-dual mr-1"><span>Sign in</span></a></li>
                    <li><a href="{% url 'users:signup' %}" class="btn btn-dual mr-1">Sign up</a></li>
                {% else %}
                    <li><a href="{% url 'users:logout' %}" class="btn btn-dual mr-1">Log out</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>